//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.25 at 08:37:41 PM ICT 
//


package com.assistant.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Exrate" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CurrencyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Buy" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="Transfer" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="Sell" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateTime",
    "exrate",
    "source"
})
@XmlRootElement(name = "ExrateList")
public class ExrateList {

    @XmlElement(name = "DateTime", required = true)
    protected String dateTime;
    @XmlElement(name = "Exrate")
    protected List<Exrate> exrate;
    @XmlElement(name = "Source", required = true)
    protected String source;

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the exrate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exrate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExrate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Exrate }
     * 
     * 
     */
    public List<Exrate> getExrate() {
        if (exrate == null) {
            exrate = new ArrayList<Exrate>();
        }
        return this.exrate;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CurrencyName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Buy" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="Transfer" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="Sell" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Exrate {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "CurrencyCode")
        protected String currencyCode;
        @XmlAttribute(name = "CurrencyName")
        protected String currencyName;
        @XmlAttribute(name = "Buy")
        protected Float buy;
        @XmlAttribute(name = "Transfer")
        protected Float transfer;
        @XmlAttribute(name = "Sell")
        protected Float sell;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the currencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyCode() {
            return currencyCode;
        }

        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyCode(String value) {
            this.currencyCode = value;
        }

        /**
         * Gets the value of the currencyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyName() {
            return currencyName;
        }

        /**
         * Sets the value of the currencyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyName(String value) {
            this.currencyName = value;
        }

        /**
         * Gets the value of the buy property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getBuy() {
            return buy;
        }

        /**
         * Sets the value of the buy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setBuy(Float value) {
            this.buy = value;
        }

        /**
         * Gets the value of the transfer property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getTransfer() {
            return transfer;
        }

        /**
         * Sets the value of the transfer property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setTransfer(Float value) {
            this.transfer = value;
        }

        /**
         * Gets the value of the sell property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getSell() {
            return sell;
        }

        /**
         * Sets the value of the sell property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setSell(Float value) {
            this.sell = value;
        }

    }

}
